### ISSUE TITLE
Add feature: Register service

### ISSUE THREAD

**Issue by blacknosugar** [andriydruk/BonjourBrowser#2]
Hi Andriy! I tried your app and it's working great. Maybe you can add the feature to register a service. Background: I use Unison in Terminal to sync files with my phone. I'd like to configure Unison to sync to hostname.local instead an IP address.

Just add a switch on the menu bar and advertise a _workstation._tcp service on 'hostname'.local like Avahi does.

**Comment by varadgunjal** [comment]
Yes please. I would like to test registration on an Android device and discovery through an iOS device using this project.

**Comment by andriydruk** [comment]
Hi, I added `register service` feature to new build in [beta channel](
https://play.google.com/apps/testing/com.druk.bonjour.browser). I'm planning to test it for a few days and then I'll roll out it to production.
Also, keep in mind that this feature is available only for developers. Please check that `Developer option` is enabled on your device.

**Comment by blacknosugar** [comment]
Many thanks, Andriy! Will give it a try.
