### ISSUE TITLE
Release 2.0.2

### ISSUE THREAD

**Issue by PhilippSelenium** [andriydruk/BonjourBrowser#27]
The last release for play store was on June 2017. Is there any chance we can get a release with the fixes made since then?

**Comment by andriydruk** [comment]
✅ Done

New release **2.0.7** available in [Google Play](https://play.google.com/store/apps/details?id=com.druk.servicebrowser)

**Comment by PhilippSelenium** [comment]
@andriydruk  Thanks!

**Comment by andriydruk** [comment]
And in [Huawei App Gallery](https://appgallery.huawei.com/#/app/C102507637)
